# Generated by Django 4.0.4 on 2022-05-15 13:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('reciever', models.CharField(max_length=30)),
                ('foodItem', models.CharField(max_length=30)),
                ('pickedUp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('label', models.CharField(choices=[('F', 'Fresh'), ('S', 'Stale')], max_length=2)),
                ('postedBy', models.EmailField(max_length=254)),
                ('pickedUp', models.BooleanField(default=False)),
                ('pickedUpBy', models.CharField(blank=True, max_length=70)),
                ('pickLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('pickLng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('memberOf', models.CharField(max_length=70)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
