# Generated by Django 4.0.4 on 2022-05-15 06:27

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('label', models.CharField(choices=[('F', 'Fresh'), ('S', 'Stale')], max_length=2)),
                ('postedBy', models.EmailField(max_length=254)),
                ('pickedUp', models.BooleanField(default=False)),
                ('pickedUpBy', djongo.models.fields.EmbeddedField(model_container=api.models.Organization)),
                ('pickLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('pickLng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestBy', models.EmailField(max_length=254)),
                ('assigned', djongo.models.fields.EmbeddedField(model_container=api.models.FoodItem)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('memberOf', djongo.models.fields.EmbeddedField(model_container=api.models.Organization)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
